name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: MicaForEveryone.MicaForEveryone
          installers-regex: 'MicaForEveryone-\w+-Release-Installer\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
